name: Linter
on: pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
